from django.urls import path

from . import projects_views
from .models import SessionTypes

app_name = "bots"

urlpatterns = [
    path(
        "create/",
        projects_views.CreateProjectView.as_view(),
        name="create-project",
    ),
    path(
        "<str:object_id>",
        projects_views.ProjectDashboardView.as_view(),
        name="project-dashboard",
    ),
    path(
        "<str:object_id>/bots",
        projects_views.ProjectBotsView.as_view(session_type=SessionTypes.BOT),
        name="project-bots",
    ),
    path(
        "<str:object_id>/app_sessions",
        projects_views.ProjectBotsView.as_view(session_type=SessionTypes.APP_SESSION),
        name="project-app-sessions",
    ),
    path(
        "<str:object_id>/bots/create",
        projects_views.CreateBotView.as_view(),
        name="create-bot",
    ),
    path(
        "<str:object_id>/bots/<str:bot_object_id>",
        projects_views.ProjectBotDetailView.as_view(),
        name="project-bot-detail",
    ),
    path(
        "<str:object_id>/app_sessions/<str:bot_object_id>",
        projects_views.ProjectBotDetailView.as_view(),
        name="project-app-session-detail",
    ),
    path(
        "<str:object_id>/bots/<str:bot_object_id>/recordings",
        projects_views.ProjectBotRecordingsView.as_view(),
        name="project-bot-recordings",
    ),
    path(
        "<str:object_id>/bots/<str:bot_object_id>/participant_events/export",
        projects_views.ProjectBotParticipantEventsExportView.as_view(),
        name="project-bot-participant-events-export",
    ),
    path(
        "<str:object_id>/credentials",
        projects_views.ProjectCredentialsView.as_view(),
        name="project-credentials",
    ),
    path(
        "<str:object_id>/project",
        projects_views.ProjectProjectView.as_view(),
        name="project-project",
    ),
    path(
        "<str:object_id>/edit",
        projects_views.EditProjectView.as_view(),
        name="project-edit",
    ),
    path(
        "<str:object_id>/keys",
        projects_views.ProjectApiKeysView.as_view(),
        name="project-api-keys",
    ),
    path(
        "<str:object_id>/keys/create/",
        projects_views.CreateApiKeyView.as_view(),
        name="create-api-key",
    ),
    path(
        "<str:object_id>/keys/<str:key_object_id>/delete/",
        projects_views.DeleteApiKeyView.as_view(),
        name="delete-api-key",
    ),
    path(
        "<str:object_id>/settings/zoom-oauth-app/",
        projects_views.CreateZoomOAuthAppView.as_view(),
        name="create-zoom-oauth-app",
    ),
    path(
        "<str:object_id>/settings/zoom-oauth-app/delete/",
        projects_views.DeleteZoomOAuthAppView.as_view(),
        name="delete-zoom-oauth-app",
    ),
    path(
        "<str:object_id>/settings/credentials/",
        projects_views.CreateCredentialsView.as_view(),
        name="create-credentials",
    ),
    path(
        "<str:object_id>/settings/credentials/delete/",
        projects_views.DeleteCredentialsView.as_view(),
        name="delete-credentials",
    ),
    path(
        "<str:object_id>/webhooks/",
        projects_views.ProjectWebhooksView.as_view(),
        name="project-webhooks",
    ),
    path(
        "<str:object_id>/webhooks/create/",
        projects_views.CreateWebhookView.as_view(),
        name="create-webhook",
    ),
    path(
        "<str:object_id>/webhooks/<str:webhook_object_id>/delete/",
        projects_views.DeleteWebhookView.as_view(),
        name="delete-webhook",
    ),
    path(
        "<str:object_id>/billing/",
        projects_views.ProjectBillingView.as_view(),
        name="project-billing",
    ),
    path(
        "<str:object_id>/billing/checkout/",
        projects_views.CreateCheckoutSessionView.as_view(),
        name="create-checkout-session",
    ),
    path(
        "<str:object_id>/billing/checkout/success/",
        projects_views.CheckoutSuccessView.as_view(),
        name="checkout-success",
    ),
    path(
        "<str:object_id>/billing/autopay/",
        projects_views.ProjectAutopayView.as_view(),
        name="project-autopay",
    ),
    path(
        "<str:object_id>/billing/autopay/stripe_portal/",
        projects_views.ProjectAutopayStripePortalView.as_view(),
        name="project-autopay-stripe-portal",
    ),
    path(
        "<str:object_id>/team/",
        projects_views.ProjectTeamView.as_view(),
        name="project-team",
    ),
    path(
        "<str:object_id>/team/invite/",
        projects_views.InviteUserView.as_view(),
        name="invite-user",
    ),
    path(
        "<str:object_id>/team/users/edit",
        projects_views.EditUserView.as_view(),
        name="edit-user",
    ),
    path(
        "<str:object_id>/calendars",
        projects_views.ProjectCalendarsView.as_view(),
        name="project-calendars",
    ),
    path(
        "<str:object_id>/calendars/<str:calendar_object_id>",
        projects_views.ProjectCalendarDetailView.as_view(),
        name="project-calendar-detail",
    ),
    path(
        "<str:object_id>/calendars/<str:calendar_object_id>/events/<str:event_object_id>",
        projects_views.ProjectCalendarEventDetailView.as_view(),
        name="project-calendar-event-detail",
    ),
    path(
        "<str:object_id>/settings/google-meet-bot-login/create/",
        projects_views.CreateGoogleMeetBotLoginView.as_view(),
        name="create-google-meet-bot-login",
    ),
    path(
        "<str:object_id>/settings/google-meet-bot-login/<str:login_object_id>/delete/",
        projects_views.DeleteGoogleMeetBotLoginView.as_view(),
        name="delete-google-meet-bot-login",
    ),
    # Don't put anything after this, it will redirect to the dashboard
    path(
        "<str:object_id>/",
        projects_views.RedirectToDashboardView.as_view(),
        name="project-unrecognized",
    ),
    path(
        "<str:object_id>/<path:extra>",
        projects_views.RedirectToDashboardView.as_view(),
        name="project-unrecognized",
    ),
]
